# This workflow will build and publish a .NET project to NuGet
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Create NuGet package
      run: dotnet pack --no-build --output ./nuget-packages
    - name: Publish to NuGet
      env:
        NUGET_AUTH_TOKEN: ${{secrets.nuget_api_key}}
      run: dotnet nuget push ./nuget-packages/Scrutinize.*.nupkg --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.nuget_api_key }}" --skip-duplicate